### ISSUE TITLE
Demo code fails to work.

### ISSUE THREAD

**Issue by bhagdave** [WillSewell/pusher-http-rust#30] opened 2022-05-07 17:32 UTC
Is this still supported?  I was browsing around looking for something like this and tried the code against and got numerous compilation errors which were fixed with changes to cargo.toml for Tokio and Hyper.  But then I just keep getting errors when doing anything with the pusher.
Here is the backtrace
   Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/pusher_test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/pusher-0.4.3/src/request.rs:36:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
   4: pusher::request::send_request::{{closure}}
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/pusher-0.4.3/src/request.rs:36:24
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: pusher::client::Pusher<C>::_channels::{{closure}}
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/pusher-0.4.3/src/client.rs:419:85
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   8: pusher::client::Pusher<C>::channels::{{closure}}
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/pusher-0.4.3/src/client.rs:372:29
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  10: pusher_test::main::{{closure}}
             at ./src/main.rs:14:12
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  12: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/park/thread.rs:263:54
  13: tokio::coop::with_budget::{{closure}}
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/coop.rs:102:9
  14: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  15: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  16: tokio::coop::with_budget
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/coop.rs:95:5
  17: tokio::coop::budget
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/coop.rs:72:5
  18: tokio::park::thread::CachedParkThread::block_on
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/park/thread.rs:263:31
  19: tokio::runtime::enter::Enter::block_on
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/enter.rs:151:13
  20: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/thread_pool/mod.rs:81:9
  21: tokio::runtime::Runtime::block_on
             at /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/mod.rs:477:43
  22: pusher_test::main
             at ./src/main.rs:18:3
  23: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5

**Comment by WillSewell** [comment] 2022-05-08 21:14
Which demo are you referring to? Do you mean https://github.com/WillSewell/pusher-http-rust/blob/master/examples/auth_server.rs. Could you upload a minimal example that I can use to reproduce the problem?

**Comment by bhagdave** [comment] 2022-05-09 07:53
Hi Will, I was referring to the example code at https://docs.rs/pusher/latest/pusher/.

I have changed it slightly to just grab channels.
[rust-pusher-example.txt](https://github.com/WillSewell/pusher-http-rust/files/8649734/rust-pusher-example.txt)

**Comment by WillSewell** [comment] 2022-05-10 21:22
Thank you. I've found out what the issue is: https://github.com/WillSewell/pusher-http-rust/pull/32.

Once that is merged (I'll try and do a bit more testing tomorrow), you'll be able to run demo code like this:

```rust
extern crate pusher; // imports the `pusher` module

use pusher::{PusherBuilder}; // brings the PusherBuilder struct into scope

#[tokio::main(flavor = "current_thread")]
async fn main() {
  // initializes a Pusher object with your app credentials
  let pusher = PusherBuilder::new("1407771", "28b6f52545badd6d33b2", "be5b7ebecc2ef210e2e2").finalize();

  // triggers an event called "my_event" on a channel called "test_channel", with the payload "hello world!"
  let result = pusher.trigger("test_channel", "my_event", "hello world!").await;
  match result {
    Ok(events) => println!("Successfully published: {:?}", events),
    Err(err) => println!("Failed to publish: {}", err),
  }
}
```

**Comment by WillSewell** [comment] 2022-05-10 21:22
Thank you. I've found out what the issue is: https://github.com/WillSewell/pusher-http-rust/pull/32.

Once that is merged (I'll try and do a bit more testing tomorrow), you'll be able to run demo code like this:

```rust
extern crate pusher; // imports the `pusher` module

use pusher::{PusherBuilder}; // brings the PusherBuilder struct into scope

#[tokio::main(flavor = "current_thread")]
async fn main() {
  // initializes a Pusher object with your app credentials
  let pusher = PusherBuilder::new("APP_ID", "APP_KEY", "APP_SECRET").finalize();

  // triggers an event called "my_event" on a channel called "test_channel", with the payload "hello world!"
  let result = pusher.trigger("test_channel", "my_event", "hello world!").await;
  match result {
    Ok(events) => println!("Successfully published: {:?}", events),
    Err(err) => println!("Failed to publish: {}", err),
  }
}
```

**Closed as completed** 2022-05-11 10:39 UTC
